# This is a basic workflow to help you get started with Actions

name: PublishOnStudentsRepo

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2


    # Use gitless because with plain git just doesn't work.
    - name: Install gitless
      run: |
        sudo pip install wheel
        sudo pip install gitless
        which gl

    # Runs a set of commands using the runners shell
        # Runs a single command using the runners shell
    - name: Merge the current state of the teachers repo onto the students repo
      env:
        SSHPASS: ${{ secrets.SSHPASS }}
      run: |
        gl remote -d mongolia2020 || true
        gl remote --create mongolia2020 "https://elviejo79:${SSHPASS}@github.com/iohkedu/haskell-mongolia-2020.git"
        gl branch -d mongolia || true
        gl branch --create mongolia
        gl switch mongolia
        gl branch --set-upstream mongolia2020/master
        gl merge master
        gl publish
